server:
  port: ${PORT:8080}

app:
  version: ${APP_VERSION:1.0.0}
  enviroment: ${APP_ENVIROMENT:Enviroment DEV}

spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgres://${DB_HOST:}:${DB_PORT:}/${DB_NAME}
    password: ${DB_PASSWORD:}
    username: ${DB_USER:}
    hikari:
      maximum-pool-size: ${DB_MAX_POOL_SIZE:10}
      minium-idle: ${DB_MIN_IDLE:5}
      connection-timeout: ${DB_CONNECTION_TIMOUT:3000}
    jpa:
      database: POSTGRESQL
      generated-ddl: false
      hibernate:
        ddl-auto: none
      show-sql: ${SHOW_SQL:true}
    sql:
      init:
        plataform: postgres